spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    urL: jdbc:mysql://database-pinit.c4wybh857q9a.ap-northeast-2.rds.amazonaws.com/pinit
    username: admin
    password: pinit123

  security:
    jwt:
      header: Authorization
      prefix : Bearer
      # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
      # echo 'jsh-springboot-and-jwt-tutorial-this-is-for-generating-jwt-secretkey-base64'|base64
      secret: anNoLXNwcmluZ2Jvb3QtYW5kLWp3dC10dXRvcmlhbC10aGlzLWlzLWZvci1nZW5lcmF0aW5nLWp3dC1zZWNyZXRrZXktYmFzZTY0Cg==
      access-token-expired-at: 3600000
      refresh-token-expired-at: 604800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    defer-datasource-initialization: true
#    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: AKIA4FBINOGC5JQYWKE4
      secret-key: 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
    s3:
      bucket: snapmap-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    snapmap-cloud-front-domain: d3b7b3nw9cqnmc.cloudfront.net

springdoc:
  # request media type 의 기본 값
  default-consumes-media-type: application/json
  # response media type 의 기본 값
  default-produces-media-type: application/json
  # 스웨거에서 제공하는 ui 라이브러리 설정
  swagger-ui:
    # swagger HTML 문서 경로
    path: /swagger-ui.html
    # swagger-ui를 사용할 것인지 여부
    enabled: true
  # 스웨거 api문서 설정
  api-docs:
        # spring boot 웹 애플리케이션의 api를 OpenAPI 3을 이용하여 json 형식화 한것의 경로
        path: /swagger/api-docs
        # 스웨거 api문서를 사용할지 여부
        enabled: true
pinnit-cloud-front-domain: d3b7b3nw9cqnmc.cloudfront.net
