spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    urL: jdbc:mysql://database-pinit.c4wybh857q9a.ap-northeast-2.rds.amazonaws.com/pinit
    username: admin
    password: pinit123

  security:
    jwt:
      header: Authorization
      prefix : Bearer
      # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
      # echo 'this-is-for-generating-jwt-secretKey-base64-for-pinnit-project'|base64
      secret: dGhpcy1pcy1mb3ItZ2VuZXJhdGluZy1qd3Qtc2VjcmV0S2V5LWJhc2U2NC1mb3ItcGlubml0LXByb2plY3QK
      access-token-expired-at: 3600000
      refresh-token-expired-at: 604800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: AKIA4FBINOGC5JQYWKE4
      secret-key: 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
    s3:
      bucket: snapmap-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    pinnit-cloud-front-domain: d3b7b3nw9cqnmc.cloudfront.net