name: Java CI with Gradle
env:
  S3_BUCKET_NAME: pinnit-dep
  
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute Permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
        
    # build한 후 프로젝트를 압축한다.
    - name: Make zip file
      run: zip -r ./pinnit-deploy.zip .
      shell: bash
    # Access Key와 Secret Access Key를 통해 권한을 확인한다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    # 압축한 프로젝트를 S3로 전송한다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./pinnit-deploy.zip s3://$S3_BUCKET_NAME/pinnit-deploy.zip 
      
